# Generated by Django 4.1.5 on 2023-01-13 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, default='Неизвестный тип', max_length=255, verbose_name='Тип инцидента')),
                ('slug', models.SlugField(editable=False, unique=True)),
            ],
            options={
                'verbose_name': 'Тип',
                'verbose_name_plural': 'Типы',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, default='Неизвестный инцидент', max_length=255, verbose_name='Название инцидента')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('legal', models.CharField(choices=[('YES', 'Легетимно'), ('NONE', 'Не определено'), ('NO', 'Нарушение')], default='NONE', max_length=5, verbose_name='Легетимность')),
                ('ip', models.GenericIPAddressField(blank=True, default='0.0.0.0', null=True, protocol='IPv4', verbose_name='Ip адресс источника')),
                ('hostname', models.CharField(blank=True, default='ARM', max_length=255, null=True, verbose_name='Имя компьютера источника')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='imitation.category', verbose_name='Тип инцидента')),
            ],
            options={
                'verbose_name': 'Инцидент',
                'verbose_name_plural': 'Инциденты',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExampleIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, default='Неизвестный инцидент', max_length=255, verbose_name='Название известного инцидента')),
                ('legal', models.CharField(choices=[('YES', 'Легетимно'), ('NONE', 'Не определено'), ('NO', 'Нарушение')], default='NONE', max_length=5, verbose_name='Легетимность')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='imitation.category', verbose_name='Тип инцидента')),
            ],
            options={
                'verbose_name': 'Известный инцидент',
                'verbose_name_plural': 'Известные инциденты',
                'ordering': ['category'],
            },
        ),
    ]
