# Generated by Django 4.1.5 on 2023-01-04 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imitation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='hostname',
            field=models.CharField(blank=True, default='ARM', max_length=255, null=True, verbose_name='Имя компьютера источника'),
        ),
        migrations.AddField(
            model_name='incident',
            name='ip',
            field=models.CharField(blank=True, default='0.0.0.0', max_length=255, null=True, verbose_name='Ip адресс источника'),
        ),
    ]
