# Generated by Django 4.1.5 on 2023-01-04 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imitation', '0002_incident_hostname_incident_ip'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExpamleIncident',
            new_name='ExampleIncident',
        ),
    ]
