# Generated by Django 4.1.5 on 2023-01-06 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imitation', '0003_rename_expamleincident_exampleincident'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exampleincident',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='imitation.category', verbose_name='Тип инцидента'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='ip',
            field=models.GenericIPAddressField(blank=True, default='0.0.0.0', null=True, protocol='IPv4', verbose_name='Ip адресс источника'),
        ),
    ]
