# Generated by Django 4.1.5 on 2023-01-06 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imitation', '0006_alter_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(editable=False, unique=True),
        ),
    ]
