# Generated by Django 4.1.5 on 2023-01-06 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imitation', '0007_alter_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='legal_too',
            field=models.CharField(choices=[('True', 'Легетимно'), ('None', 'Не определено'), ('False', 'Нарушение')], default='None', max_length=5, verbose_name='Легетимность'),
        ),
    ]
