# Generated by Django 4.1.5 on 2023-01-06 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imitation', '0008_incident_legal_too'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incident',
            name='legal_too',
        ),
        migrations.AlterField(
            model_name='incident',
            name='legal',
            field=models.CharField(choices=[('True', 'Легетимно'), ('None', 'Не определено'), ('False', 'Нарушение')], default='None', max_length=5, verbose_name='Легетимность'),
        ),
    ]
