# Generated by Django 4.1.5 on 2023-01-06 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imitation', '0009_remove_incident_legal_too_alter_incident_legal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='legal',
            field=models.CharField(choices=[('FR', 'Легетимно'), ('SO', 'Не определено'), ('JR', 'Нарушение')], default='JR', max_length=5, verbose_name='Легетимность'),
        ),
    ]
