# Generated by Django 4.1.5 on 2023-01-07 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imitation', '0011_alter_incident_legal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exampleincident',
            name='legal',
            field=models.CharField(choices=[('YES', 'Легетимно'), ('NONE', 'Не определено'), ('NO', 'Нарушение')], default='NONE', max_length=5, verbose_name='Легетимность'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='legal',
            field=models.CharField(choices=[('YES', 'Легетимно'), ('NONE', 'Не определено'), ('NO', 'Нарушение')], default='NONE', max_length=5, verbose_name='Легетимность'),
        ),
    ]
